# Generated by Django 6.0 on 2026-03-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ecommerce', '0001_initial'), ('ecommerce', '0002_remove_productmodel_title_productmodel_name'), ('ecommerce', '0003_productmodel_color_productmodel_description_and_more'), ('ecommerce', '0004_productmodel_short_description')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.TextField(default='Producto sin nombre')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_dimensions', models.CharField(blank=True, max_length=120, null=True)),
                ('seller', models.CharField(blank=True, max_length=120, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
