# Generated by Django 6.0 on 2026-01-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name',
            field=models.TextField(default='Producto sin nombre'),
            preserve_default=False,
        ),
    ]
