# Generated by Django 6.0 on 2026-03-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_productmodel_title_productmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_dimensions',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='seller',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
