# Generated by Django 6.0 on 2026-03-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_productmodel_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='publish_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
